// generated by:
// go generate
// DO NOT EDIT

package temblate_go

func init() {
	templates = messageTemplates{"msg1":langTemplates{"en":"Just a simple message.", "nl":"Gewoon een simpele mededeling."}, "msg2":langTemplates{"en":"Your nickname is {{ .Nickname }}!\n"}}
}
