// generated by:
// go generate
// DO NOT EDIT

package temblate_go

func init() {
	templates = MessageTemplates{"msg1":LangTemplates{"en":"Just a simple message.", "nl":"Gewoon een simpele mededeling."}, "msg2":LangTemplates{"en":"Your nickname is {{ .Nickname }}!\n"}}
}
